# ==========================================================
# InfraPulse Server Inventory
# ==========================================================

# Format:
# hostname|ip_address|username

localhost|10.77.126.250|abhishek

# Example Servers
# app-server-1|192.168.1.101|ubuntu
# app-server-2|192.168.1.102|ubuntu
# db-server|192.168.1.103|ubuntu
