name: InfraPulse CI

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Required Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            shellcheck \
            jq \
            bc \
            curl \
            iproute2 \
            net-tools

      - name: Verify Project Structure
        run: |
          test -d automation
          test -d monitoring
          test -d dashboard
          test -d notifications
          test -d reports
          test -d multiserver

      - name: Make Scripts Executable
        run: |
          find . -type f -name "*.sh" -exec chmod +x {} \;

      - name: Run ShellCheck
        run: |
          find . -type f -name "*.sh" | while read file
          do
            echo "Checking $file"
            shellcheck "$file"
          done

      - name: Build Docker Image
        run: |
          docker build \
            -f docker/Dockerfile \
            -t infrapulse:latest .

      - name: Verify Docker Image
        run: |
          docker images

      - name: CI Completed
        run: echo "InfraPulse CI Pipeline Passed Successfully!"
